name: benchmark
channels:
  - conda-forge
dependencies:
  - python=3.8
  - numpy
  - pandas
  - tblib
  - attrs
  - python-nds2-client
  - gwpy
  - python-ldas-tools-framecpp
  - pip
  - pip:
    - -r requirements.txt